JNU-econovation/econo-recruit-fe

- frontend/components/user/SignInForm.component.tsx
signin input의 placeholder 오타를 수정했습니다.
closes #21
> fix: input placeholder 오타 수정

- frontend/components/admin/Board.component.tsx
- frontend/components/applicant/applicantNode/Label.component.tsx
- frontend/components/applicant/applicantNode/Timeline.component.tsx
- frontend/components/application/Navbar.component.tsx
- frontend/components/application/Question.component.tsx
- frontend/components/application/applicationLayout/RadioForCheck.component.tsx
- frontend/components/application/applicationLayout/Vertical.component.tsx
- frontend/components/application/applicationLayout/timeline/Timeline.component.tsx
- frontend/components/application/applicationLayout/timeline/TimelineRow.component.tsx
- frontend/components/application/applicationNode/Text.component.tsx
- frontend/components/common/Checkbox.component.tsx
- frontend/components/common/Radio.component.tsx
- frontend/components/common/SortList.component.tsx
- frontend/components/common/Txt.component.tsx
- frontend/components/common/board/Board.component.tsx
- frontend/components/kanban/card/Card.component.tsx
- frontend/components/kanban/content/work/Label.component.tsx
- frontend/package.json
- frontend/pnpm-lock.yaml
- frontend/src/utils/cn.ts
- tailwind-merge , clsx dependencies가 추가되었습니다.
- twMerge, clsx를 사용한 유틸함수 cn()를 생성하였습니다.
- props로 class를 받는 컴포넌트의 경우 cn()을 사용하여 합쳐주었습니다.
- 기존 classnames와 동일한 작업을 하므로 classnames를 cn으로 교체하였습니다.
- classnames dependencies를 제거하였습니다.
- cn을 부적절하게 사용한 부분이 있는지 확인 부탁드립니다.
- 기존의 조건적으로 className을 설정하는 부분을 모무 `{}`로 분리해주었습니다. 이 과정에서 삼항연산자를 단순 조건식으로 변경하다보니 약간의 중복 로직이 발생한 부분이 생겼습니다. 이 부분에 대해서 피드백 부탁드립니다!
- 조건문이 복잡한 부분은 변수로 빼두었습니다. 변수명이 적절한지 확인 부탁드립니다.
- 올바른 tailwind-custom-color 가 적용되었는지 확인 부탁드립니다
- closes #7
> refactor: classname대신 tailwind-merge + clsx를 합쳐서 사용한다.

- frontend/components/applicant/Junction.component.tsx
- frontend/components/application/Junction.component.tsx
- frontend/components/application/JunctionOrLayout.tsx
- frontend/components/application/Layout.component.tsx
- frontend/components/application/Question.component.tsx
- frontend/components/application/applicationLayout/BooleanTextarea.component.tsx
- frontend/components/application/applicationLayout/Horizontal.componet.tsx
- frontend/components/application/applicationLayout/RadioForCheck.component.tsx
- frontend/components/application/applicationLayout/Vertical.component.tsx
- frontend/components/application/applicationLayout/timeline/Timeline.component.tsx
- frontend/components/application/applicationNode/JustText.component.tsx
- frontend/components/application/applicationNode/NextButton.component.tsx
- frontend/components/application/applicationNode/Radio.component.tsx
- frontend/components/application/applicationNode/RadioByTwoRank.component.tsx
- frontend/components/application/applicationNode/Text.component.tsx
- frontend/components/application/sendApplication.ts
- frontend/src/constants/applicant/25.ts
- frontend/src/constants/applicant/26.ts
- frontend/src/constants/applicant/type.d.ts
- frontend/src/constants/application/25.ts
- frontend/src/constants/application/26.ts
- frontend/src/constants/application/26/designer.ts
- frontend/src/constants/application/26/developer.ts
- frontend/src/constants/application/26/manager.ts
- frontend/src/constants/application/type.d.ts
- frontend/src/stores/application/index.ts
- as 키워드를 제거하였습니다.
- applicationNode, applicationQuestion의 타입의 형태를 바꾸었습니다.
- closes #10
> refactor: change ApplicationNode, ApplicationQuestion Type

- frontend/components/common/navbar/NavbarOperation.tsx
1.  admin 사용자가 navbar에 관리자 페이지가 나타나지 않는 문제를 해결하였습니다.
2. 경로가 잘못 import된 파일을 수정했습니다.
* 1번 변경사항은 혹시 의도하신거라면..... 다시 수정하겠습니다.
closes #68
> fix: admin navbar와 import 경로 수정

- frontend/components/application/Question.component.tsx
- frontend/components/application/applicationNode/NextButton.component.tsx
- frontend/src/functions/getApplicationName.ts
- frontend/src/functions/validator.ts
- 로직을 재 작성하여 개선하였습니다
먼가 파일 위치가 잘 못되어 있는거 같지만... 지금은 저기 있어도 될꺼 같습니다!
- closes #56
> fix: next button 가 적용이 안되는 문제

- frontend/components/kanban/content/DetailWork.component.tsx
- frontend/components/kanban/content/work/EditorOrViewer.component.tsx
- frontend/components/kanban/content/work/WorkDetailLeft.component.tsx
- frontend/components/kanban/content/work/WorkDetailRight.component.tsx
- frontend/src/apis/work/index.ts
- frontend/src/constants/index.ts
- frontend/src/functions/formatter.ts
- 정렬 기준이 소문자로 변경되어 이에 맞춰 수정하였습니다.
- 브랜치를 여러번 변경하다가 score 관련 commit이 포함된 것 같습니다..!
closes
> fix: URI 규칙을 준수하도록 정렬 기준을 소문자로 수정한다.

- frontend/components/application/applicationNode/NextButton.component.tsx
- frontend/src/functions/replacer.ts
- 위와 같은 타입에러를 해결했습니다.
closes #96
> fix: NextButton에서 발생한 타입 에러를 해결한다.

- frontend/app/(WithNavbar)/layout.tsx
- frontend/src/constants/index.ts
- navbar의 generation에 숫자형 부분만 담기도록 parseInt()를 사용하였습니다.
- 큰 변동사항이 없습니다! 해결 방법이 괜찮은 방법인지, 혹은 더 좋은 방법이 있을지, 조언 부탁드립니다!
- 추가적으로 추가된 로직과 관련하여 리팩토링할 부분이 있는지 확인 부탁트립니다!
closes #93
> fix: navbar의 generation이 제대로 보이지 않는 버그 수정

- frontend/src/apis/applicant/index.ts
- API url을 swagger에 맞춰 수정했습니다.
closes #98
> fix: id로 지원서를 조회하는 API의 url을 수정한다

- .github/workflows/buildtest.yml
빌드를 자동화 하여 검증합니다.
pull repuest 시 생성되고, 일단은 production이 없으므로 고정된 API를 사용합니다.
- ~~잘.. 되겠죠?~~ 잘되네요!
> build: ci 워크플로우 작성

- frontend/components/common/navbar/Button.tsx
- frontend/components/kanban/Navbar.component.tsx
- frontend/src/constants/kanban/27.ts
- 칸반보드의 메뉴바 부분을 현 TF의 부서에 맞추어 변경하였습니다.
- 간단하게 className부분을 cn 유틸함수를 사용하여 리팩토링 하였습니다.
- 추가적인 변경할 부분이 있을까요..?
closes #109
> feat: 신입모집TF 개편에 따라 칸반 메뉴바 내용 수정

- frontend/app/application/backup/route.ts
- frontend/src/hooks/useSendApplication.tsx
메시지가 보내지지 않는 것 문제를 해결한다
- closes #112
> fix: 메시지가 보내지지 않는 것 문제를 해결한다

- frontend/src/hooks/useSendApplication.tsx
- 2024년 1학기 기준 2024년 03월 15일 입니다.
- closes #129
> refactor: 마무리 시간을 만들었습니다

- frontend/components/common/navbar/LogoutBtn.tsx
- frontend/src/apis/user/index.ts
로그인 방식을 쿠키 방식으로 수정함에 따라서 로그아웃을 서버에서 관리하도록 수정하였습니다. 
급한 이슈인 만큼 빠르게 머지하겠습니다!
closes #135
> feat: 로그아웃 기능을 수정한다.

- frontend/src/hooks/useSendApplication.tsx
필수 질문을 작성하지 않고 지원서가 제출되는 버그가 있어 필수 질문을 모두 확인하도록 수정하였습니다.
closes #139
> fix: 필수 질문을 모두 확인하도록 수정

- frontend/src/hooks/useApplication.tsx
> fix: change time

- frontend/app/application/backup/route.ts
백엔드에서 이메일 보내는 로직이 있어서 이메일이 2번 보내지는 버그가 있어서 프론트에서 이메일 보내는 요청을 주석처리 하였습니다.
closes #181
> bug: 이메일 보내는 요청 주석 처리

- frontend/components/kanban/DragDrop.component.tsx
- frontend/components/kanban/column/ColumnWithBackButton.component.tsx
- frontend/src/apis/kanban/index.ts
- API 호출에서 query parameter로 기수를 받아올 수 있도록 구현하였습니다. 
- 요구사항 관련해서는 아래 Slack 참고 바랍니다.
https://econovation-2018.slack.com/archives/C07HX1GTR6C/p1725554497771049
- 현재 백엔드에도 구현되지 않은 기능이라, 머지는 부회장님 승인하에 진행하도록 하겠습니다.
- closes #191
> feat: 칸반보드 조회 API 수정

- frontend/src/stores/kanban/Kanban.atoms.ts
197번 PR을 머지하고 Github Action을 봤는데 build error를 발견해서 수정하였습니다....
앞으로는 확인하고 merge 하겠습니다 !
closes #200
> hotfix: 빌드 시 발생하는 오류 제거

- frontend/components/interview/Board.tsx
- frontend/components/interview/PageNavbar.tsx
- frontend/src/apis/interview/index.ts
- closes #226 
잘못된 쿼리 파라미터 수정입니다 !
잘못된 쿼리 파라미터를 수정하였습니다. ( sortType -> order)
> bug: 잘못된 api 파라미터 수정

- frontend/src/constants/application/29/developer.ts
#257 
- #257 
5번과 7번 질문에 동일한 값이 입력됩니다.
application/developer 폴더의 7번 질문 name 을 reason 에서 experience 로 변경했습니다.
X
X
> fix: 개발자 질문의 5번과 7번이 동일하게 입력되는 버그 수정

- frontend/src/hooks/useApplication.tsx
> fix: 지원서가 올바르게 제출되지 않던 버그 수정

- frontend/components/application/applicationNode/RadioByTwoRank.component.tsx
- frontend/src/constants/application/29/manager.ts
- closes #261 
- 요구사항이 반영되지 않는 지원서 일부를 수정했습니다.
- 필수 질문 중, 프로젝트 희망 분야에서 1순위 및 2순위 선택이 필수 질문 표시가 되지 않는 문제를 해결했습니다. 
- 기획자 5번 질문이 navbar와 질문지의 문장이 일치하지 않는 문제를 해결했습니다.
> refactor: 29기 지원서 요구사항 반영

- frontend/src/constants/application/29.ts
- closes #268 
-  기본 인적 사항의 학년과 학기가 undefined로 표시되는 문제를 해결했습니다.
> bug: 기본 인적 사항의 학년과 학기가 undefined로 표시되는 문제 해결

- frontend/src/functions/validator.ts
- closes #269 
필수 확인 사항 질문의 input 의 validate가 '확인했습니다.'가 포함되어있는지를 확인하도록 수정하였습니다.
input에사 사용하는 validate로직 부분을 '확인했습니다.' 를 포함하는지를 확인하도록 하였습니다. 
빠른 확인 부탁드립니다 🙇🏻‍♂️
> fix: 필수 확인 사항 질문의 input 의 validate가 '확인했습니다.'가 포함되어있는지를 확인하도록 수정

- frontend/components/applicant/DetailRight.component.tsx
- frontend/src/constants/applicant/29/designer.ts
- frontend/src/constants/applicant/29/developer.ts
- frontend/src/constants/applicant/29/manager.ts
- closes #272 
TF팀이 보는 칸반보드 및 지원 현황 페이지에서 아래의 문제점들이 존재하였습니다. 
- 개발자 질문에서 기존에 존재하던 `협업 여부 + 하고 싶은 프로젝트` 질문의 잔재로 현재 받고 있지 않은, 앞으로 하고싶은 프로젝트 질문이 보인다.
- 개발자 질문의 답변에서 8, 9번 질문의 답변이 뒤바뀌어 보인다. 
- 질문들이 너무 간략화되어있다. 
상단의 문제들은 기존에 만들어 두었던 상수데이터(applicant/...)를 수정하여 해결할 수 있었습니다. 
크게 없습니다!
추가적으로 prettier가 적용되어서 DetailRight.component.tsx  값이 변경되었는데, 무시해도 괜찮을 것 같습니다!
혹시나 빌드가 안되는 문제가 있다면, 말씀해주세요!
크게 없습니다!
간단한 변경이라서 편하게 봐주셔도 될 것 같습니다.
혹시나 제가 놓친 부분이 있거나, 혹은 해당 상수값을 변경함으로써 사이드이펙트가 발생한다면 말씀해 주시면 감사할 것 같습니다.🙇🏻‍♂️
> fix: 개발자 질문에서 8, 9번 질문의 답변이 뒤바뀌어 보이는 버그 해결

- frontend/src/constants/applicant/29/developer.ts
- closes #274 
이슈에서 설명했듯, 지원 현황 페이지에서 개발자의 7번 질문의 답변이 올바르게 보이지 않던 버그가 존재하였습니다. 
해당 부분은 올바르게 서버에서 전달해주고 있었으나, applicant/29/developer.ts 상수값이 정확하지 않아 applicantDataFinder() 함수로 상수값을 가져오려고 할 때 제대로된 값을 가져오지 못하였습니다. 
applicant/29/developer.ts 파일을 올바르게 수정하였습니다. 
크게 없습니다!
혹시나 놓친 부분이 있는지 확인 부탁드립니다..!
> fix: 개발자의 7번 질문의 답변이 보이지 않던 버그 수정

- frontend/components/interview/modal/score/AvgScore.tsx
- frontend/components/interview/modal/score/InterviewScore.tsx
- frontend/components/interview/modal/score/InterviewerScore.tsx
- frontend/components/interview/modal/score/MyScore.tsx
- frontend/components/interview/modal/score/MyScoreForm.tsx
- frontend/components/interview/modal/score/ScoreCell.tsx
- frontend/components/interview/modal/score/ScoreInput.tsx
- frontend/src/constants/applicant/29.ts
- frontend/src/functions/formatter.ts
- closes #281 
인재상 변경에 따른 record 점수 필드를 변경합니다
**TF에서 급하게 변경을 요청해 변수만 변경해 pr 요청 날립니다!** 
(오늘부터 면접이 진행되어 곧 점수 반영을 시작한다고 합니다!)
- 변수 변경
- 스코어 필드 28기 -> 29기로 임포트 변경
변경 부분은 크게 없습니다! 
기능적인 문제가 없다면 머지하고 
변경해볼사항들이 있다면 추후 이슈를 만들어 진행하겠습니다!
수정 전 반영했던 점수들은 배열로 그대로 받고 있기에 전의 모습으로 적용된 모습을 보여주고 있습니다!
현재 변경사항을 반영한다면 당장은 문제 없을 거라고 생각합니다(일단 점수등록을 하기 전이기에..)
> refactor: 인재상 변경에 따른 record 점수 필드 변경

- frontend/src/functions/validator.ts
- frontend/src/hooks/useApplication.tsx
- closes #263 
- 지원서 공통문항 2번 기본 인적 사항 입력에서 양식에 맞지 않는 입력일지라도, 한 글자라도 입력이 되면 navbar가 활성화되는 문제가 있었습니다. 
- 작성된 문항을 확인할 수 있도록 하는 navbar의 취지와 맞지 않아 수정이 필요했습니다.
https://github.com/user-attachments/assets/efe7d70a-44ed-47a0-bad7-711ee31f0e87
- useAplication에서 해당 두 문항에 대한 validation을 통해 양식에 맞지 않는 입력이 들어올 시 navbar를 비활성화 할 수 있도록 수정했습니다. 
- 2~3줄 정도의 짧은 코드가 추가 되었습니다! 여전히 validation이 적용되어있지 않은 부분 혹은 컨벤션에 맞지 않는 부분을 찾으신다면 말씀 주시면 감사하겠습니다!
> bug: 지원서 연락처 및 학번 양식 일치 시에만 Navbar 활성화

- frontend/app/(WithNavbar)/admin/[generation]/on-off/page.tsx
- frontend/app/(WithNavbar)/admin/[generation]/page.tsx
- frontend/app/(WithNavbar)/admin/layout.tsx
- frontend/components/admin/AdminTabs.tsx
- frontend/components/common/Pagination.tsx
- frontend/components/recruitment/RecruitmentForm.tsx
- frontend/components/recruitment/RecruitmentStatusSection.tsx
- frontend/src/apis/recruitment/index.ts
- frontend/src/functions/recruitment.ts
- frontend/src/hooks/useRecruitmentData.tsx
- frontend/src/hooks/useRecruitmentMutations.tsx
- closes #293 
관리자가 지원서 접수기간을 체계적으로 관리할 수 있도록 c,r,d 기능을 추가했습니다.
- admin 폴더에 layout을 추가해 tab형식으로 변경했습니다.
- 접수 기간 등록: 년도, 시작일, 종료일을 설정하여 새로운 접수 기간 생성
- 현재 접수 기간 조회: 진행 중인 접수 기간을 표시
- 접수 기간 취소: 현재 진행 중인 접수 기간을 즉시 취소
- 이전 접수 기간 목록: 종료된 접수 기간들의 히스토리 조회
- RecruitmentStatusSection: 현재/이전 접수 기간을 통합 관리하는 컴포넌트
- RecruitmentForm: 새로운 접수 기간 등록 폼 컴포넌트
- useRecruitmentMutations
- src/functions 에 관련 함수들을 모아놨습니다. (필터링,포매팅 하는 함수 등..)
- 새로 알게 된 점.!
input에서 datetime-local type을 사용해서 달력 UI를 바로 구현했습니다.
> feat: 지원서 접수 기간 관리자 기능 추가
