JNU-econovation/econo-recruit-fe

frontend/tailwind.config.js

- 기존에 DEFAULT 값 선언 시 colors 객체를 불러왔는데, 이렇게 사용하면 `colors undefined` 에러가 뜹니다.
- 색상 코드를 바로 할당하는 것으로 변경했습니다. 
tailwind theme DEFAULT 값 더 효율적으로 사용하는 방법을 알고 계신다면 조언 해주세요!!
closes #14

fix: tailwind.config color DEFAULT 선언 부분 변경

---

frontend/components/admin/Board.component.tsx
frontend/src/constants/admin/index.ts

- 제목이 곧 내용
- roleTranslater는 도메인(비즈니스)로직 즉 서비스 계층 로직같아 상수로 분리하지는 않았어용
closes #41

 refactor: components/admin/Board constant가 있는 문제

---

frontend/app/(WithNavbar)/admin/[generation]/page.tsx

admin/[generation]에 interviewers 쿼리와  getMyInfo 쿼리에 대해 hydration을 적용하였습니다.
어제 날린 pr과 유사합니다.
추가로 admin/[generation]에서 안쓰는 prop은 삭제했습니다.
데이터를 목적에 맞게 불러오고 있는지 확인해주세요!
closes #42

refactor: admin 페이지에 hydration 적용

---

frontend/components/common/navbar/Navbar.tsx

- 일반 페이지에서 navbar가 원래 모습이 보이도록 합니다. 칸반보드 페이지에서는 짧은 모습이 제대로 보이도록 수정하였습니다.
- 조건문 하나만 고쳐서 크게 볼 부분이 없을 듯 합니다!
[칸판 페이지 fix 전 & 후]
[다른 페이지 fix 전 & 후]
- 조건문 하나만 고쳐서 크게 볼 부분이 없을 듯 합니다!
closes #77

fix: 올바르게 navbar가 적용되도록 수정

---

frontend/components/kanban/content/DetailWork.component.tsx
frontend/components/kanban/content/work/EditorOrViewer.component.tsx
frontend/components/kanban/content/work/WorkDetailLeft.component.tsx
frontend/components/kanban/content/work/WorkDetailRight.component.tsx
frontend/src/apis/work/index.ts

[문제 상황](https://github.com/JNU-econovation/econo-recruit-fe/issues/75)
업무 전환시, 기존에 캐싱 타임이 지나지 않은 상태로 기존에 들어갔던 페이지에 들어가게 되면, 가장 최근 렌더링된 모습만 보이는 문제가 존재하였고, 이를 캐싱타임을 없애 매 요청마다 재 랜더링이 되도록 수정하였습니다.
- query의 캐싱타임을 조정하였습니다.
- 코드를 리팩토링 하였습니다.
- 부적절하게 리팩토링 된 부분을 확인해주세요! 
- 추가적인 수정사항이 있는지 확인해주세요!
closes #75

fix: 업무 전환시 내용이 제대로 보이지 않던 버그 수정

---

frontend/components/applicant/applicantNode/comment/InputForm.component.tsx

- 댓글을 제출하면 새로고침을 해야 작성된 댓글이 보이는 이슈
- invalidateQueries 코드를 수정하였습니다.
- 댓글을 아무런 텍스트 없이 제출 버튼 클릭 후, 다시 텍스트 입력 후 제출하는 경우 제대로 반영되지 않는 버그 발견
- `isPrevSubmit()` 로직을 수정하였습니다.
- 지코삼을 체크 하면 input 창에 자동으로 텍스트가 들어가는데, 체크를 해제하면 텍스트가 없어지지 않고 그대로 남아있음.
- Editor 컴포넌트의 onChange 함수를 삭제했습니다. (onNoCommentCheck와 로직 겹침)
- 개선할 사항이 있다면 알려주세요!
closes #84

refactor: 댓글 제출 시 바로 화면에 반영되게 한다.

---

frontend/components/interview/modal/score/AvgScore.tsx
frontend/components/interview/modal/score/ScoreCell.tsx

- 점수를 소수점 1자리 숫자로 고정했습니다.
- toFixed를 사용해서 구현했습니다. 더 좋은 방법이 있다면 추천해주세요!
closes #107

fix: 점수를 소수점 1자리로 반올림 해서 표시한다.

---

frontend/components/application/applicationNode/NextButton.component.tsx

- 리팩토링이라고 할 것 도 없네요 .. ㅋㅋ 아마 기능개선하면서 만지신 분들이 다 잘해주셔서 할게 별로 없었습니다
- PR Comment에 남겨두겠습니다 !
- #46 
(closed를 하는게 나을까요?)

refactor: next button 분기문 리팩토링

---

frontend/components/application/applicationLayout/RadioForCheck.component.tsx

개인정보수집 관련 전문은 노션으로 연결되기 때문에, 노션 링크를 27기에 맞춰 바꿔뒀습니다.
일단 링크를 바꿔두긴 했는데 전문이 노션에 종속되는 것보단 정적 페이지로 만들어서 관리하는 게 더 좋아보입니다..! 바로 작업을 하는 게 좋을까요? 아니면 다음 신입모집부터 적용하는 게 좋을까요?
closes #105

fix: 동의서 관련 노션 링크를 수정한다

---

frontend/src/hooks/useSendApplication.tsx

- channel이라는 배열에 `channel`과 `channelEtc`의 값을 넣었기 때문에 지원경로 입력 확인 시 channel이라는 배열을 이용했습니다.
- #104 윤성님 pr과 유사한 로직이 많아 이부분도 리펙토링을 하면 좋을 것 같습니다.
closes #103

fix: 지원경로 기타 클릭 후 값 입력 시 제출할 수 있도록 수정한다.

---

frontend/components/application/applicationLayout/RadioForCheck.component.tsx
frontend/package.json
frontend/pnpm-lock.yaml

개인정보동의 토글이 제대로 동작하지 않아, 오프라인 라이트닝 회의를 거쳐 react-use를 도입했습니다..
- closes #102

fix: 개인정보 동의 토글이 제대로 동작하지 않는 문제

---

frontend/components/application/applicationLayout/BooleanTextarea.component.tsx
frontend/components/application/applicationNode/Textarea.component.tsx
frontend/src/constants/index.ts

- 최대 글자수를 신청 페이지에 표시합니다.
- 글자 입력 시 최대 글자수를 넘지 못하도록 핸들러 함수를 추가했습니다.
closes #124

feat: 최대 글자 제한을 UI에 표시한다

---

frontend/src/functions/getApplication.ts

- booleanTextarea에 name이 숨어있었는데, 이를 parsing하지 못했습니다.
- 고로 여기에 고치며 바로 아래 있는 코드까지 의도적으로 break를 걸지 않았습니다. 이를 유념해주세요.
- closes #137

fix: booleanTextarea에서 보내지 못하는 데이터를 보낸다

---

frontend/app/application/consent/page.tsx
frontend/components/application/applicationLayout/RadioForCheck.component.tsx
frontend/src/constants/application/27.ts
frontend/src/functions/replacer.ts

개인정보 수집(공통, 포트폴리오)에 대한 전문 페이지를 만들었습니다.
동의서가 두개라서 페이지를 따로 만들까 생각도 했지만, 하나에 모아두는 것도 괜찮을 것 같다는 생각에 각각의 section에 id를 지정해두고, a 태그를 통해 해당 id에 이동하는 방식으로 구현했습니다.
(추가로.. 포트폴리오 관련 전문에 잘못된 문구를 발견해서 회장단과 논의하에 바꿨습니다.)
동의서 두개를 각각 따로 두는 게 나을까요? a 태그를 통해서 이동하게 하긴 했지만 워낙 글이 짧아서 id로 이동한다는 느낌은 크게 안들긴하네요
closes #118

feat: 개인정보 수집 전문 페이지를 구현한다.

---

frontend/app/(WithNavbar)/layout.tsx
frontend/app/kanban/[generation]/detail/page.tsx
frontend/components/common/navbar/Navbar.tsx
frontend/components/common/navbar/NavbarCell.tsx
frontend/components/common/navbar/NavbarGenerationToggle.tsx
frontend/components/common/navbar/NavbarOperation.tsx
frontend/components/common/navbar/NavbarToggle.tsx
frontend/components/kanban/column/ColumnWithBackButton.component.tsx
frontend/public/icons/lt.icon.white.svg
frontend/src/constants/applicant/28.ts
frontend/src/constants/applicant/28/designer.ts
frontend/src/constants/applicant/28/developer.ts
frontend/src/constants/applicant/28/manager.ts
frontend/src/constants/application/28.ts
frontend/src/constants/application/28/designer.ts
frontend/src/constants/application/28/developer.ts
frontend/src/constants/application/28/manager.ts
frontend/src/constants/index.ts
frontend/src/hooks/useCreateQueryString.tsx

- 새로운 신입모집이 시작됨에 따라서 CURRENT_GENERATION 을 28로 업데이트 했습니다. 
- 이에 따라서 불러오는 상수 데이터를 저장하는 28.ts 및 기타 파일들을 추가하였습니다. 이는 27기의 파일과 동일하며, tf팀의 요청사항이 있을시 변경하도록 하겠습니다. 
- 추가적으로 navbar의 탭을 리팩토링 하였습니다
- 기존 a 태그를 사용하여 전체 페이지를 리렌더링 하는 로직에서, Link 태그로 변경하여 next의 최적화 이점을 얻을 수 있도록 하였습니다.
- 현재 url을 가져오는 로직이 최상위 로직에서 props로 필요한 곳까지 전달하는 로직을 해당 컴포넌트에서 `usePathname()` 을 사용하여 가져올 수 있도록 하였습니다. 
- 기존 칸반, 면접 기록, 지원 현황 페이지에서 각각 이동 방식이 [generation] 부분을 CURRENT_GENERATION에서 가져와 사용하던 부분을 현재 url에서 가져와 generation을 사용하는 방식으로 변경하여, 만약 이전 신입모집 기록을 볼 때 라우팅이 해당 신입모집 페이지만 볼 수 있도록 수정하였습니다. 
- 이전 신입모집을 바로 볼 수 있도록 네비게이션바에 이전 신입모집 보기 버튼을 추가하였습니다. 이는 url에서 가져온 generation값이 CURRENT_GENERATION과 동일한지를 확인 후 이전 신입모집 보기 혹은 현재 신입모집 보기 버튼으로 분기처리하도록 하였습니다. 
기존에 매번 전체 회면이 새롭게 렌더링 되던 부분을 변경된 부분만 렌더링 되도록 수정하였습니다
closes #156

feat: current generation 업데이트

---

frontend/cypress/e2e/application.second-personal-information.cy.ts
frontend/cypress/support/commands.ts

- 두번째 인적사항 페이지로 이동하는 함수 구현
- 테스트 코드 구현
1. 전공 입력 + 다음 버튼 클릭
2. 전공 입력 + 복수 전공 입력 + 다음 버튼 클릭
3. 전공 입력 + 부전공 입력 + 다음 버튼 클릭
4. 전공 입력 + 복수 전공 입력 + 부전공 입력 + 다음 버튼 클릭
5. 아무것도 입력 x + 다음 버튼 클릭
6. 전공 입력 x + 복수 전공 입력 + 부전공 입력 + 다음 버튼 클릭
cypress 에서는 alert 창이 뜨지 않기 때문에 alert 창을 감지해서 console문으로 내용을 출력해주었습니다 !
closes #162

test: 두번째 기본 인적 사항 테스트 코드 작성

---

frontend/app/application/consent/page.tsx
frontend/src/constants/application/28.ts

개인 정보 수집 안내 페이지 내용을 업데이트합니다. 
- 페이지에서 사용하는 상수 데이터를 이번 신입모집 일정에 맞추어 업데이트 하였습니다.
- 페이지에서 최신 기수의 상수 데이터를 가져올 수 있도록 동적 import 로 변경하였습니다. 
- 추가적으로 이름이 모호한 느낌이 있어 jsDoc으로 해당 상수에 대해서 설명을 추가하였습니다. 
- 큰 변화는 없습니다..! 더 좋은 개선 사항이 있을지 궁금 하기도 하네요!
- 상수 데이터에 설명을 추가한게 조금 어색해 보이기도 하네요. 굳이 라는 생각이 들기도 합니다. 이와 관련해서 의견 부탁드립니다!
closes #169

feat: 개인정보 수집 안내 페이지 상수 데이터 업데이트

---

frontend/cypress/e2e/application.personal_info.cy.ts

- 사용자는 이름을 5글자까지 입력 가능하다.
- 사용자는 연락처에 숫자만 기입할 수 있다.
- 사용자는 연락처에 11자리의 숫자까지만 입력할 수 있다.
- 사용자가 연락처에 숫자를 입력한다면 자동으로 휴대전화 포맷으로 보여진다
- 사용자가 연락처를 입력한 시점부터 연락처 형식에 맞게 작성을 완료하지 못한 경우 “연락처를 입력해주세요.” 라는 안내문구가 뜬다.
- 사용자는 학번에 6자리 숫자를 입력할 수 있다.
- 사용자가 학번을 입력한 시점부터 학번 형식에 맞게 작성을 완료하지 못한 경우 “학번을 입력해주세요.” 라는 안내문구가 뜬다.
- 사용자는 학적상태(재학/휴학)를 기입할 수 있다.
- 사용자는 학년을 선택한 후 학기를 1학기, 2학기 중 선택할 수 있다.
- 기본 인적 사항(첫번째 페이지)에 모든 내용을 양식에 맞게 추가하지 않았을 경우 “필수 질문을 작성해주세요.”라는 alert창이 뜬다.
- 질문 제목 네비게이션을 통한 질문 페이지 이동은, 현재 작성 해놓은 가장 나중의 페이지까지만 이동이 가능하다.
- 질문 제목 네비게이션을 통한 이후 질문 페이지 이동 시에는 반드시 현재 작성하고 있는 질문지에 대한 유효성 검증이 성공해야만 한다.
- closes #161

test: 첫번째 인적사항 페이지 테스트 코드

---

frontend/cypress/e2e/application.other-questions.cy.ts
frontend/cypress/support/commands.ts

- 사용자는 향후 계획활동을 기입할 수 있다.
- 사용자는 지원 경로를 중복으로 선택가능하다.
- 사용자는 지원 경로에서 기타를 선택할 경우 기타 지원 경로에 관한 내용을 입력할 수 있다.
- 사용자는 아무것도 작성 및 선택하지 말고 다음버튼을 누를 시, “지원경로를 선택해주세요.”라는 alert창이 뜬다.
- 사용자는 향후 계획활동을 기입하지 않고 다음버튼을 누를 시, “지원경로를 선택해주세요.”라는 alert창이 뜬다. (지원경로 선택 = true)
- 사용자는 지원경로를 선택하지 않고 다음버튼을 누를 시, “지원경로를 선택해주세요.”라는 alert창이 뜬다. (향후 계획활동 작성 = true)
- 사용자는 지원경로 중 “기타” 만 선택하고 다음버튼을 누를 시, “지원경로를 선택해주세요.”라는 alert창이 뜬다. (향후 계획활동 작성 = true)
- 사용자는 “기타”가 아닌 지원경로 하나 이상과, “기타”를 선택하고 다음버튼을 누를 시, 다음 페이지로 넘어간다. (향후 계획활동 작성 = true, 지원경로 선택 = true )
- 사용자는 지원경로 중 “기타”만 선택하고 기타에 관한 내용을 기입한 이후, 다음 버튼을 누를 시, 다음페이지로 넘어간다. (향후 계획활동 작성 = true, 지원 경로 선택 = true)
- 기타 질문 사항 페이지로 이동하는 goOtherQuestions 함수 구현
- 기타 질문 사항 e2e 테스트
건규님께서 만드신 checkAlert 함수가 실제 alert문의 내용을 입력하지 않아도 cypress가 동작할 때 에러를 출력하지 않는 것 같습니다.
```
it("사용자는 …
```

test: 기타 질문 사항 e2e 테스트

---

frontend/src/constants/application/28.ts
frontend/src/hooks/useApplication.tsx

- END_DATE 상수에 프로퍼티를 추가하였습니다.
- 지원서를 제출하기 전에 모집 마감 기간 전인지 확인하는 코드에서 마감 기간이 27기 신입 모집 마감 날짜 기간으로 돼있어서 END_DATE를 import 하는 코드로 변경하였습니다.
closes #173

refactor: 신입 모집 마감 날짜 수정

---

frontend/components/applicant/applicantNode/Timeline.component.tsx

지원 현황 페이지의 면접 가능시간 부분의 날짜가 올바르게 보이도록 수정하였습니다.
before
after
큰 변경점이 아니라서 가볍게 보셔도 괜찮을 것 같습니다! 
closes #186

fix: 지원 현황 페이지의 면접 가능시간 부분 올바르게 보이도록 수정

---

frontend/src/constants/applicant/28.ts
frontend/src/constants/applicant/28/designer.ts
frontend/src/constants/applicant/28/developer.ts
frontend/src/constants/applicant/28/manager.ts

질문지를 업데이트 하면서 지원현황 페이지의 질문을 업데이트 하지 않아 지원현황 페이지에서 이전 질문이 보이던 버그가 존재하였습니다.
이를 지원현황 페이지의 질문 업데이트를 통해서 해결하게 되었습니다. 
- 지원현황 페이지의 면접 시간 기입 질문을 업데이트하였습니다.
- 지원현황 페이지의 면접 시간 기입 질문의 질문 번호를 업데이트하였습니다.
<details>
<summary>수정된 모습 보기</summary>
</details>
큰 변경점이 없어 가볍게 확인하셔도 좋을 것 같습니다...!
closes #188

fix: 지원현황 페이지의 질문이 이전 기수 질문으로 보이던 버그 수정

---

frontend/app/application/done/page.tsx
frontend/components/kanban/DragDrop.component.tsx
frontend/components/kanban/column/ColumnWithBackButton.component.tsx
frontend/src/apis/kanban/index.ts
frontend/src/apis/user/index.ts
frontend/src/functions/axios.ts

- 기존의 interceptors가 제대로 작동하지 않게 작성되어 있어서 작동이 잘 되게 변경하였습니다. (로컬 스토리지에 accessToken가 있으면 api request에 Authorization에 넣어주었습니다.)
- 로그인 성공 시 로컬 스토리지에 accessToken 저장하였습니다.
- 로그아웃 시 로컬 스토리지의 accessToken을 삭제하였습니다.
- 백엔드 요구사항에 맞게 api 요청의 쿼리 파라미터에 year를 추가하였습니다.
- 지원서 작성하고 나오는 페이지에서 여기 버튼을 클릭 시 기존에는 고정된 url로 이동하였는데 접속한 url에 따라 유동적으로 변경하였습니다.
closes #190

feat: 개발 서버에서 로그인이 가능하게 기능 추가

---

frontend/components/applicant/applicantNode/Portfolio.tsx

`fileUrlforPlanner` 를 Portfolio 컴포넌트에서 읽어올 수 있도록 수정하였습니다.
- closes #206

fix: 기획자 포트폴리오가 보이지 않는 문제 해결

---

frontend/components/applicant/Board.tsx
frontend/components/common/board/Board.tsx
frontend/components/common/board/BoardCell.component.tsx
frontend/components/common/board/BoardModal.tsx
frontend/components/common/board/BoardTable.tsx
frontend/components/interview/Board.tsx
frontend/components/passState/PassStateLabel.tsx
frontend/src/apis/interview/index.ts
frontend/src/constants/index.ts
frontend/src/functions/replacer.ts
frontend/src/hooks/useModalState.ts
frontend/src/hooks/useSearchQuery.tsx

- #203 지원현황 목록 페이지에서 합불상태를 조회할 수 있다.
- #204 면접기록 목록 페이지에서 합불상태를 조회할 수 있다.
- 지원현황/면접기록 페이지가 동일한 컴포넌트를 공유하고 있어서, 편의상 같은 브랜치에서 작업한 점 양해부탁드립니다.
- 기존 컴포넌트를 리팩토링하였습니다.
- 합불상태를 보여주는 Txt 컴포넌트는 #205 를 참고해 만들었습니다. 추후 원하신다면 재사용가능한 컴포넌트로 두루 사용하게 해도 괜찮을듯합니다.
- closes #203 
- closes #204

feat: 지원현황/면접기록 목록페이지에서 합불상태를 조회할 수 있다.

---

frontend/components/common/navbar/NavbarManagePassState.tsx

기존에 네브바에 관리자가 아닌 계정으로 접속시 "관리자만 접근이 가능합니다." 문구가 보였습니다. 
이는 이전에 저의 [pr](https://github.com/JNU-econovation/econo-recruit-fe/pull/205)에서 해당 컴포넌트의 요구사항에 맞지 않는 수정을 해서 문제가 발행하였습니다. 
네브바의 합/불 관리 페이지 버튼은 사용자의 role을 가져오는 도중, 그리고 가져온 role이 관리자가 아닌 경우에 아무런 것도 보이지 않도록 해야 한다고 생각합니다. (실제로 이와 동일한 동작(?)을 하는 네브바의 관리자 페이지 부분도 동일하게 작성되어 있습니다.)
이에 맞추어 ( `isLoading`, `!data`, .`role !== "ROLE_OPERATION`" )인 상에서는 아무런 것도 보여주지 않도록 변경하였습니다. 
<details>
<summary>관리자 페이지 부분 로직</summary>
```
export const NavbarOperation = ({
currentType,
isShort,
}: NavbarOperationProps) => {
const currentPath = usePathname();
const generation = currentPath.split("/")[2];
const { data: userData } = useQuery(["user"], getMyInfo);
if (!userData) {
return <div></div>; // 여기또한 아무런 값을 보여주지 않고 있습니다. 
}
if (userData.role !== …
```

fix: 관리자가 아닌 사용자에게 navbar에 불필요한 문자가 보이는 버그 수정

---

frontend/components/applicant/DetailLeft.component.tsx
frontend/components/applicant/applicantNode/CustomResource.component.tsx
frontend/components/kanban/column/ColumnWithBackButton.component.tsx
frontend/src/apis/applicant/index.ts
frontend/src/utils/applicant/index.ts

- 지원자의 지원 상태를 변경하는 api 함수 구현 (patchApplicantState)
- 특정한 지원자의 상태를 가져오는 api 함수 구현 (getApplicantState)
- 관리자와 회장단에게만 지원자의 상태를 변경할 수 있는 버튼을 보이게 함.
- 지원자의 지원 상태를 학과 옆에 표시
회장단과 관리자만 지원자의 지원 상태 변경이 가능
- 해결 방안
1. 회장단과 관리자에게만 버튼이 보이도록 한다.
2. 모든 사람에게 버튼이 보이도록 하고 권한이 없는 사람이 버튼을 클릭 시 alert를 띄운다.
저는 1번이 맞다고 생각하여 1번으로 구현하였는데 다른 분들의 의견도 궁금합니다 !
closes #199

feat: 칸반보드 상세 페이지에서 지원 상태 확인 및 지원 상태 변경 가능하게 구현

---

frontend/components/applicant/applicantNode/Label.component.tsx
frontend/components/kanban/content/work/Label.component.tsx
frontend/src/apis/applicant/index.ts
frontend/src/apis/work/index.ts

- list를 렌더링하는데 중복이 될 수 있는 값을 key로 사용해, 재조정 알고리즘이 꼬이는 문제를 해결하였습니다.
- 빠르게 머지 부탁해용~
- closes #214

[FE] fix: 칸반보드의 라벨이 계속 늘어나는 문제 해결

---

frontend/components/applicant/Board.tsx
frontend/components/applicant/_applicant/ApplicantDetailLeft.tsx
frontend/components/applicant/_applicant/_applicantNode/CustomResource.tsx
frontend/components/passState/ApplicantsList.tsx
frontend/src/apis/applicant/index.ts
frontend/src/apis/passState/index.tsx

기존에 지원 현황 페이지의 사용자 클릭시 올바르게 사용자의 정보가 보이지 않는 버그가 존재하였습니다.
이는 같은 ui를 가지는 칸반 디테일 페이지와 지원 현황 디테일 페이지가 다른 비지니스를 가져 발생하였습니다. 
ui 로직을 공통 컴포넌트로 만들어서 이를 해결하고자 하였습니다. 
다만, 여기서는 공통 컴포넌트를 만들기만 하였으며, 적용은 지원 현황 디테일 페이지에만 적용이 되어있습니다.
추후 이슈를 파서 칸반보드 디테일 페이지에도 적용하도록 하겠습니다. 
(현재 파일명에 _가 붙어있는 것은 문제 해결 전의 기존 컴포넌트와 동일한 이름을 가지는 컴포넌트로 만들어 해당 문제를 해결하고자 하였기 때문입니다. 이는 추후 칸반보드 디테일 페이지에도 적용하게 될 때 제거하도록 하겠습니다.)
- 코드적인 문제 상황이 있을지 확인 부탁드립니다. 개발용에서는 문제점은 발견되지 않았습니다. 
closes #202 #218

fix: 지원서 현황 페이지에서 사용자의 이름 정보가 보이지 않는 버그

---

frontend/components/passState/ApplicantsList.tsx
frontend/src/apis/passState/index.tsx

합불 변경 요청 메서드가 patch이지만, post로 되어있어 올바르게 반영이 되지 않던 버그가 존재하였습니다. 
이를 patch로 올바르게 수정하였습니다. 
- 큰 변경사항이 아니라 가볍게 보시면 될 것 같습니다.
closes #221

fix: 합불 상태 변경 요청 method가 올바르지 않았던 버그 수정

---

frontend/components/applicant/applicantNode/Portfolio.tsx
frontend/src/utils/applicant/index.ts

1. changeIntactUrl 함수 생성 : http 혹은 https 프로토콜이 붙지 않은 url에 대해 http 프로토콜을 붙여준다.
2. Link 태그의 target="_blank"로 인해 발생할 수 있는 보안 문제를 해결하기 위해 rel="noopener noreferrer" 속성 추가
프로토콜이 붙지 않은 url에 대해서 http 프로토콜을 붙이도록 함수를 구현했는데 https에 대한 처리는 어떻게 해야할 지 모르겠네요. (https로 접근을 해야하는 사이트인데 http로 접근하면 문제가 발생할 수도 있을 것 같습니다.)
closes #223

bug: 지원자의 프로토콜이 붙지 않은 포트폴리오 링크에 대한 버그 수정

---

frontend/components/applicant/applicantNode/Portfolio.tsx
frontend/src/utils/applicant/index.ts

- closes #228 
기존의 프로토콜이 붙지 않은 url에 대해서 프로토콜을 붙여주는 로직이 모든 예외 사항을 잡아주지 않습니다.
예시는 이슈에 있습니다 !
해당 로직을 삭제하였습니다 !
추후에 지원서 작성 시 url을 입력하는 부분의 input을 변경하는게 좋아보입니다.
url에 대한 설명 : url 
ex) 노션 : 노션 url

refactor: 프로토콜이 붙지 않은 url에 대해서 프로토콜을 붙여주는 로직 삭제

---

frontend/app/signin/page.tsx
frontend/app/signup/page.tsx
frontend/components/user/SignInForm.component.tsx
frontend/components/user/SignUpForm.component.tsx
frontend/src/functions/validator.ts

- closes #234 
비밀번호 유효성 검사 수정입니다.
- 특수 문자 최소 1자 이상
- 숫자 최소 1자 이상
- 전체 문자 10자 이상
백엔드의 유효성 검사와 맞게 프론트도 변경하였습니다.
비밀 번호 input에서 minLength 속성을 제거하였는데 이유는 minLength를 지키지 않았을 때 크롬 자체적으로 경고 표시가 나오는 ui가 별로라고 생각했기 때문입니다.
회원 가입 성공 시 메인 페이지로 이동하던 로직은 로그인 페이지로 이동하게 변경하였습니다.

bug: 비밀 번호 유효성 검사 수정

---

frontend/.eslintrc.json

- closes #244
빌드 시 발생하는 prettier 에러를 해결합니다.
eslintrc 의 rules에  "useTabs": false를 추가했습니다.
prettierrc의 "tabWidth": 2가 useTabs가 false일 때만 적용되다보니 발생한 문제라고 생각합니다.

bug: 빌드 시 prettier 에러 해결

---

frontend/src/hooks/useApplication.tsx

#265 
필수 질문을 모두 입력해도 제출이 되지 않음.
제출이 되도록 수정
canApplicationNext 에서 메세지가 없을 때 true 를 리턴하도록 했습니다.
getRequiredQuestionValidateMessage 에서 오류 메세지가 없다면 undefined 를 return 해도 될 지, 아니면 다른 특정 값을 넣는게 좋을지 의견 있으시면 말씀해주시면 감사하겠습니다!

fix: canApplicationNext 에서 오류 메세지가 없을 때 true 리턴하도록 수정

---

frontend/src/constants/index.ts

- closes #277 
칸반 보드 상세 페이지에서 사용자가 입력한 구체적인 분야에 대한 내용이 렌더링되지 않는 문제입니다.
칸반 보드 상세 페이지에서는 post 요청으로 request body에 담긴 필드에 대한 값을 받아오는데 구체적인 분야에 해당 하는 필드를 넣어주지 않았습니다.
상수 데이터에 구체적인 분야에 해당하는 필드 추가

fix: 칸반보드 상세 페이지에서 구체적인 분야 불러오기

---

frontend/components/applicant/Board.tsx
frontend/components/applicant/_applicant/ApplicantDetailLeft.tsx
frontend/components/applicant/_applicant/_applicantNode/CustomResource.tsx
frontend/components/applicant/applicantNode/CustomResource.component.tsx
frontend/components/common/CardApplicantStatusLabel.tsx
frontend/components/kanban/card/Card.component.tsx
frontend/components/passState/ApplicantsList.tsx
frontend/src/functions/passState.ts
frontend/src/hooks/applicant/useApplicantById.tsx
frontend/src/hooks/applicant/useOptimisticApplicantPassUpdate.tsx
frontend/src/hooks/useModalState.ts

- closes #250 
- 지원현황 -> 합/불 체크 시 아무런 피드백도 없기에 사용자는 체크가 잘 이루어졌는지 확인하기 어려웠습니다.
- 합/불 체크가 3곳(지원현황, 칸반보드, 관리자 합/불)에서 이루어지고 있는데 관련 로직들이 전부 따로 관리되고 있었기에 이를 통일화 합니다.
- 기존 코드에서도 쿼리 무효화를 시켜주어 합/불 후 새로운 쿼리를 불러왔지만, 지원 현황에서의 데이터들은 모든 데이터를 불러와 useState의 setter를 통해 필터링 시켜 관리 되고 있었고, 상태 변화가 없었기에 합/불 피드백이 이루어지지 않았습니다.
-> 합/불 상태를 확인할 수 있는 로직을 만들고 합/불 상태를 CardApplicantStatusLabel 컴포넌트에서 전부 보여주게 변경
- optimistic updates 훅을 만들어 합/불 처리를 통일화.
- 모든 지원자들의 데이터를 불러와 필터링 해서 사용하기 보단, 결국에는 한 지원자의 정보만을 조회할 수 있는(합/불 상태 포함) api 가 필요하다고 생각합니다. 추 후 백엔드와 얘기해보고 새로 이슈 만들어 보겠습니다🫡
- 현재 만든 useApplicantId 훅 또한 모든 사용자를 가져와 필터링 후 사용하고 있습니다.

refactor: 합/불 라벨링 사용자 피드백 추가 & 공통 로직 설정

---

frontend/app/(WithNavbar)/admin/[generation]/page.tsx
frontend/components/admin/Board.component.tsx
frontend/package.json
frontend/src/apis/applicant/index.ts
frontend/src/apis/interview/index.ts
frontend/src/apis/work/index.ts

- closes #279 
기존에는 지원 현황 및 칸반보드 페이지에서 면접관 부분에 모든 사용자의 이름이 보였습니다. 
이번에 모든 사용자의 이름이 보이는 것이 아닌, 이번 신입모집에 참여한 사용자만 보이도록 수정하도록 TF팀의 요청이 있었습니다.
이에 따라서 (기존에 면접관 리스트를 가져오는 api에서 role에 따른 필터링 기능이 추가되었고, ) 필터링을 할 수 있도록 변경하였습니다. 
면접관을 가져오는 getAllInterviewerWithOrder api 함수를 roles 쿼리 스트링을 받을 수 있도록 수정하였습니다. 
order만 받는 api가 아니므로, 이름을 getInterviewer로 변경하였습니다. 
api에서 반복되는 타입을 추가적으로 정의해주었습니다. 
```
export type Role =
| "ROLE_GUEST"
| "ROLE_TF"
| "ROLE_OPERATION"
| "ROLE_PRESIDENT";
export type RoleName = "GUEST" | "TF" | "OPERATION" | "PRESIDENT";
```
크게 없습니다!
혹시나 제가 놓친 부분이 있는지 확인 부탁드립니다! 🙇🏻‍♂️

feat: 면접관 리스트 조회 API의 스팩 변경 및 면접관 리스트 조회 시 "현재 기수 면접관"만 조회하도록 수정

---

frontend/app/(WithNavbar)/interview/[generation]/page.tsx
frontend/components/applicant/ApplicantList.tsx
frontend/components/applicant/PageNavbar.tsx
frontend/components/common/PageNavbar.component.tsx
frontend/components/interview/IntervieweeList.tsx
frontend/components/interview/InterviewerList.tsx
frontend/components/interview/PageNavbar.tsx
frontend/src/hooks/applicant/index.ts
frontend/src/hooks/applicant/useApplicantPaginationParams.ts
frontend/src/hooks/applicant/useApplicantsQuery.ts
frontend/src/hooks/interview/index.ts
frontend/src/hooks/interview/useAllInterviewRecordQuery.ts
frontend/src/hooks/interview/useIntervieweePaginationParams.ts
frontend/src/hooks/interview/useInterviewerPaginationParams.ts

- closes #254 
기존에 신입모집 지원 현황 페이지와, 신입모집 면접 기록 페이지에서 페이지 이동을 하게되면 깜빡임 현상이 있었습니다.
이는 이후 탐색 페이지를 prefetch하지 않아 loading 상태로 인해 발생하는 문제 였습니다.
이에 따라 #254 에서 @smb0123 님이 제공해주신 Link 태그와 곁들여,
client 단에서의 prefetch도 진행하였습니다.
#67 PR을 보면 배경님이 구현해주신 좋은 SSR 예시가 있습니다. 제가 구현한 컴포넌트에도 SSR prefetch를 할 수 있지만,
저는 client prefetch로 구현하였습니다. 이유는 만약 SSR prefetch를 하게된다면 검색어 쿼리로 인해 필요 이상으로 페이지를 요청보내고 받을 수 있다고 생각했기 때문입니다.
따라서 서버에서 그려주는 건 레이아웃 부분만 있어도 충분하다고 판단하였습니다. 더 좋은 의견이 있다면 PR에 달아주세요.
기존 훅 로직을 적당한 계층에 맞게 추상화 하였습니다.
코드 구조를 제 편한대로 구현하였는데, 의문점이나 개선점 있다면 주저없이 댓글 달아주세요!
가급적 최종 시작 전에 Merge된다면 감사드리겠습니다 :)
No response

feat: pagination page의 prefetch 로직
